language: cpp
sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

script:

  # Libtermkey and libunibilium packages from ubuntu Artful
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libt/libtermkey/libtermkey1_0.20-2_amd64.deb
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libt/libtermkey/libtermkey-dev_0.20-2_amd64.deb
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/u/unibilium/libunibilium0_1.2.0-1_amd64.deb
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/u/unibilium/libunibilium-dev_1.2.0-1_amd64.deb
  - sudo dpkg -i libunibilium0_1.2.0-1_amd64.deb libtermkey1_0.20-2_amd64.deb libtermkey-dev_0.20-2_amd64.deb libunibilium-dev_1.2.0-1_amd64.deb

  # Depot tools
  - if [ ! -e depot_tools/gclient ]; then git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git; fi
  - export PATH="$PATH:"`pwd`/depot_tools

  # Compilation
  - mkdir build && cd build
  - CC=gcc-6 CXX=g++-6 cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

  # Tests
  - make check
